---
- name: hello world
  hosts: bun
  remote_user: basu
  become: yes
  become_method: sudo

  vars: 
    phone_model: nexus-5

  tasks:
  - name: install vlc
    apt: name=vlc state=latest
  - name: debugging
    debug: msg="This is the value of the variable {{phone_model}}"
  - name: another task
    apt: name=git

- name: another play
  hosts: bun
  become: yes
  become_method: sudo

  tasks:
  - name: Update apt cache
    apt: update_cache=yes
