---
- name: hello world
  hosts: bun
  remote_user: basu
  become: yes
  become_method: sudo

  vars: 
    phone_model: nexus-5

  pre_tasks:
    - shell: echo 'before roles'

  roles:
    - vlc

  post_tasks:
    - shell: echo 'after rules'
